name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: create new folder
        run: mkdir new_folder

      - name: list folders
        run: ls -al

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: clone repository
        uses: actions/checkout@v5

      - run: ls -al
      - run: npm -v
      - run: node -v

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Final Step
        run: ls -al

  job4:
    runs-on: ubuntu-latest
    needs: [job2, job3]
    steps:
      - name: Another Final Step
        run: ls -al
